version: 2
orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      MAVEN_OPTS: -Xmx6400m
    steps:
      ## Checkout the source code
      - checkout

      ## Restore any files that may have been cached from previous jobs
      - restore_cache:
          keys:
            - sortpom-cache-{{ checksum "pom.xml" }}
            - sortpom-cache- # fallback in case previous cache key is not found

      ## cache the dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: sortpom-cache--{{ checksum "pom.xml" }}

      - run:
          name: Run unit tests
          command: ./mvnw test