version: 2.1
orbs:
  maven: circleci/maven@0.0.12
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      MAVEN_OPTS: -Xmx6400m
    steps:
      ## Checkout the source code
      - checkout

      ## Restore any files that may have been cached from previous jobs

      - run:
          name: Run unit tests
          command: mvn test
workflows:
     sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
       jobs:
         - build-and-test        